<a href="https://colab.research.google.com/github/Aggeliki-Mentzini/python1/blob/main/Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
twoDarray=np.array([[1,2,3],[4,5,6]])
twoDarray


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
twoDarray.shape

(2, 3)

In [ ]:
twoDarray.ndim

2

In [ ]:
twoDarray[1]

array([4, 5, 6])

In [ ]:
twoDarray[0]

array([1, 2, 3])

In [ ]:
twoDarray[1,2]

6