<a href="https://colab.research.google.com/github/Aggeliki-Mentzini/python1/blob/main/Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
twoDarray=np.array([[1,2,3],[4,5,6]])
twoDarray


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
twoDarray.shape

(2, 3)

In [ ]:
twoDarray.ndim

2

In [ ]:
twoDarray[1]

array([4, 5, 6])

In [ ]:
twoDarray[0]

array([1, 2, 3])

In [ ]:
twoDarray[1,2]

6

In [1]:
A=[1,2,3,4]

In [2]:
print(A[0])

1


In [3]:
best_friends=["Natalie","Bob"]

In [4]:
print(best_friends)

['Natalie', 'Bob']


In [6]:
best_friends[0]="Nat"
print(best_friends)

['Nat', 'Bob']


In [7]:
A=[5,8,2]
max=A[0]
for i in range(len(A)):
  if A[i]>max:
    max=A[i]
print(max)

8


In [8]:
print(A[-1])

2


In [13]:
print(A[0:3])

[5, 8, 2]


In [21]:
A.append(10)
print(A)
print(len(A))

[10, 5, 8, 2, 4, 4, 10, 10]
8


In [17]:
A.insert(0,10)
print(A)

[10, 5, 8, 2, 4, 4, 10]


In [19]:
print(len(A))

7


In [25]:
B=["a"]
print(type(B))

<class 'list'>


In [23]:
A.extend(B)
print(A)

[10, 5, 8, 2, 4, 4, 10, 10, 'a']


In [24]:
print(type(A))

<class 'list'>


In [27]:
last=A.pop( )
print(last)

a


In [28]:
print(A)

[10, 5, 8, 2, 4, 4, 10, 10]


In [30]:
A.clear()
print(A)

[]


In [41]:
oura_sto_tameio=[]
print(oura_sto_tameio)
oura_sto_tameio.append("Bob")
print(oura_sto_tameio)
oura_sto_tameio.append("Tom")
print(oura_sto_tameio[i])
print(oura_sto_tameio)
efyge=oura_sto_tameio.pop(0)
print(efyge, "served","emeinan oi", oura_sto_tameio)

[]
['Bob']
Tom
['Bob', 'Tom']
Bob served emeinan oi ['Tom']


In [45]:
A=[]
number=float(input("Dose prwto arithmo"))
A.append(number)
number=float(input("Dose deftero arithmo"))
A.append(number)
print(A)
number=float(input("Dose tretiko arithmo"))
A.append(number)
print(A)

Dose prwto arithmo2
Dose deftero arithmo6
[2.0, 6.0]
Dose tretiko arithmo1
[2.0, 6.0, 1.0]


In [46]:
A.sort()
print(A)

[1.0, 2.0, 6.0]


In [48]:
tainies=["deiw","ejdbje"]
agapimeni=input("Dose tainiko")


if agapimeni in tainies:
  print("Yparxei")
else:
  print("Den yparxei")

Dose tainikowwwwwwwwwww
Den yparxei


In [50]:
i=1
while i<=5:
  print(i)
  i+=1

1
2
3
4
5


In [57]:
x=input("Dose arithmo")
while x!="quit":
  print(int(x)**2)
  x=input("Dose arithmo")

print("telos")

Dose arithmo4
16
Dose arithmoquit
telos


In [58]:
for i in range(1,6):
  print(i)

1
2
3
4
5


In [59]:
for i in range(19,12,-1):
  print(i)

19
18
17
16
15
14
13


In [62]:
for i in range(1,29+1,2):
  if i%3==0:
    print(i)

3
9
15
21
27


In [63]:
A=[]
for i in range(0,1000+1,2):
  A.append(i)
print(A)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

In [74]:
x=int(input("Dose arithmo"))
while x<3 and x>20:
  print(x)
  x=int(input("Dose arithmo"))
A=[]
for i in range(0,x):
  y=int(input("Dose arithmo"))
  while y<10 or y>20:
    print(y)
    y=int(input("Lathos, Dose arithmo apo 10 mexri 20"))
  A.append(y)
A.sort()
print(A)

Dose arithmo3
Dose arithmo12
Dose arithmo1
1
Lathos, Dose arithmo apo 10 mexri 2010
Dose arithmo20
[10, 12, 20]


In [86]:
krimenos=6
x=int(input("dose arithmo"))
while x!=krimenos:
   if x>krimenos:
     print("mantepse kapoion mikrotero")
   else:
     print("mantepse kapoion megalutero")

   x=int(input("dose pali arithmo"))
else:
  print("ton mantepses")

dose arithmo5
mantepse kapoion megalutero
dose pali arithmo7
mantepse kapoion mikrotero
dose pali arithmo6
ton mantepses


In [ ]:
3